import "./globals.css";
import "./css/media-query.css"

export const metadata = {
  title: "learning-impact-zambia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body id="body">
        <div className="main-box">
          {children}
        </div>
      </body>
    </html>
  );
}
